proplan/urls.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from django.urls import path, re_path, include
from proplan.views import pages, api, auto

app_name = 'proplan'

abs_patterns = [
    path('', auto.check, name='check'),
    path('create/', auto.CreateView.as_view(), name='create'),
    path('upload/', auto.UploadView.as_view(), name='upload'),
]

api_patterns = [
    path('attachments/', api.AttachmentsView.as_view(), name='attachments'),
    path('attachments/<int:id>/', api.AttachmentView.as_view(), name='attachment'),
    path('comments/', api.CommentsView.as_view(), name='comments'),
    path('comments/<int:id>/', api.CommentView.as_view(), name='comment'),
    path('executors/', api.ExecutorsView.as_view(), name='executors'),
    path('executors/<int:id>/', api.ExecutorView.as_view(), name='executor'),
    path('roles/', api.RolesView.as_view(), name='roles'),
    path('roles/<int:id>/', api.RoleView.as_view(), name='role'),
    path('stages/', api.StagesView.as_view(), name='stages'),
    path('stages/<int:id>/', api.StageView.as_view(), name='stage'),
    path('start/<int:id>/', api.StartView.as_view(), name='start'),
    path('stop/<int:id>/', api.StopView.as_view(), name='stop'),
    path('subprojects/', api.SubprojectsView.as_view(), name='subprojects'),
    path('subprojects/<int:id>/', api.SubprojectView.as_view(), name='subproject'),
    path('tasks/', api.TasksView.as_view(), name='tasks'),
    path('tasks/<int:id>/', api.TaskView.as_view(), name='task'),
    path('trackers/', api.TrackersView.as_view(), name='trackers'),
    path('trackers/<int:id>/', api.TrackerView.as_view(), name='tracker'),
    path('versions/', api.VersionsView.as_view(), name='versions'),
    path('versions/<int:id>/', api.VersionView.as_view(), name='version'),
    path('preview/', api.PreviewView.as_view(), name='preview'),
]


pages_patterns = [
    path('', pages.IndexView.as_view(), name='index'),
    path('attachments/', pages.AttachmentsView.as_view(), name='attachments'),
    path('configuration/', pages.ConfigurationView.as_view(), name='configuration'),
    path('comments/', pages.CommentsView.as_view(), name='comments'),
    path('console/', pages.ConsoleView.as_view(), name='console'),
    path('login/', pages.LoginView.as_view(), name='login'),
    path('logout/', pages.LogoutView.as_view(), name='logout'),
    path('profile/', pages.ProfileView.as_view(), name='profile'),
    path('profile/password/change/', pages.PasswordChangeView.as_view(),
         name='password_change'),
    path('search/', pages.SearchView.as_view(), name='search'),
    path('tasks/', pages.TasksView.as_view(), name='tasks'),
    path('tasks/add/', pages.TaskFormView.as_view(), name='add_task'),
    path('tasks/<int:id>/', pages.TaskView.as_view(), name='task'),
    path('tasks/<int:id>/change/', pages.TaskFormView.as_view(), name='change_task'),
    path('versions/', pages.VersionsView.as_view(), name='versions'),
    re_path(r'^_/(?P<section>[-\w]+)/(?P<name>[-\w]+\.html)$',
            pages.UnderscoreView.as_view(), name='underscore'),
    re_path(r'^_/(?P<name>[-\w]+\.html)$',
            pages.UnderscoreView.as_view(), name='underscore'),
]

urlpatterns = [
    path('', include(pages_patterns)),
    path('abs/', include((abs_patterns, 'abs'))),
    path('api/', include((api_patterns, 'api'))),
]

proplan/views/base.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from json import loads

from django.http import QueryDict, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from proplan import forms
from proplan.decorators import access_required, abs_required


def parse_params(request):
    if request.content_type == 'application/json':
        return loads(request.body.decode('utf-8'))
    method = request.method
    if method == 'GET':
        return request.GET
    elif method == 'POST':
        return request.POST
    return QueryDict(request.body)


@method_decorator(access_required, name='dispatch')
class AccessMixin:
    """Mixing for user access."""
    def dispatch(self, *args, **kwargs):
        return super(AccessMixin, self).dispatch(*args, **kwargs)


@method_decorator(csrf_exempt, name='dispatch')
@method_decorator(abs_required, name='dispatch')
class ABSMixin:
    """Mixing for Automatic Bug System access."""
    def dispatch(self, *args, **kwargs):
        return super(ABSMixin, self).dispatch(*args, **kwargs)


class BaseUploadView(View):
    """View for uploading attachments."""

    def upload_attachment(self, request):
        form = forms.AttachmentForm(request.user, files=request.FILES)
        if form.is_valid():
            attachment = form.save()
            data = {
                'id': attachment.id,
                'name': attachment.name,
                'url': attachment.url,
                'thumb': attachment.thumb_url,
            }
            return JsonResponse(data)
        data = {'errors': form.errors.get_json_data(escape_html=True)}
        return JsonResponse(data, status=400)

    def post(self, request):
        return self.upload_attachment(request)

proplan/templates/proplan/_navbar.html
{% load i18n proplan_nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top shadow p-0">
    <div class="d-none d-xl-block col-xl-2 mr-0">
        <a class="navbar-brand" \
           href="{% url 'proplan:index' %}">{% trans 'План проекта' %}</a>
    </div>
    <a class="navbar-brand d-xl-none mx-2" \
       href="{% url 'proplan:index' %}">{% trans 'План проекта' %}</a>
    <button class="navbar-toggler mr-1" type="button" data-toggle="collapse" \
            data-target="#navbarContent" aria-controls="navbarContent" \
            aria-expanded="false" aria-label="{% trans 'Переключение навигации' %}">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
        <form class="form-inline w-100" action="{% url 'proplan:search' %}">
            <input class="form-control form-control-dark w-100" \
                   type="text" placeholder="{% trans 'Поиск' %}" \
                   aria-label="{% trans 'Поиск' %}" \
                   name="q" autofocus \
                   onfocus="this.setSelectionRange(this.value.length, this.value.length)" \
                   value="{{ request.GET.q }}">
        </form>
        <ul class="navbar-nav px-3">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" \
                   id="navbarDropdownHistory" role="button" \
                   data-toggle="dropdown" aria-haspopup="true" \
                   aria-expanded="false">
                    <span>{% trans 'История' %}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownHistory">
                    <a class="dropdown-item {% active request 'proplan:versions' %}" \
                       href="{% url 'proplan:versions' %}">
                        <span class="fa fa-fw fa-code-fork"></span>
                        <span class="ml-1">{% trans 'Версии' %}</span>
                    </a>
                    <a class="dropdown-item {% active request 'proplan:tasks' %}" \
                       href="{% url 'proplan:tasks' %}">
                        <span class="fa fa-fw fa-tasks"></span>
                        <span class="ml-1">{% trans 'Задачи' %}</span>
                    </a>
                    <a class="dropdown-item {% active request 'proplan:comments' %}" \
                       href="{% url 'proplan:comments' %}">
                        <span class="fa fa-fw fa-comments-o"></span>
                        <span class="ml-1">{% trans 'Комментарии' %}</span>
                    </a>
                    <a class="dropdown-item {% active request 'proplan:attachments' %}" \
                       href="{% url 'proplan:attachments' %}">
                        <span class="fa fa-fw fa-folder-open-o"></span>
                        <span class="ml-1">{% trans 'Вложения' %}</span>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" \
                   id="navbarDropdownSettings" role="button" \
                   data-toggle="dropdown" aria-haspopup="true" \
                   aria-expanded="false">
                    <span>{% trans 'Настройки' %}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownSettings">
                    <a class="dropdown-item {% active request 'proplan:profile' %}" \
                       href="{% url 'proplan:profile' %}">
                        <span class="fa fa-fw fa-user"></span>
                        <span class="ml-1">{% trans 'Профиль' %}</span>
                    </a>
                    <a class="dropdown-item {% active request 'proplan:configuration' %}" \
                       href="{% url 'proplan:configuration' %}">
                        <span class="fa fa-fw fa-cogs"></span>
                        <span class="ml-1">{% trans 'Конфигурация' %}</span>
                    </a>
                </div>
            </li>
            <li class="nav-item text-nowrap">
            {% if user.is_authenticated %}
                <a href="{{ LOGOUT_URL }}" \
                   class="nav-link">{% trans 'Выйти' %}</a>
            {% else %}
                <a href="{{ LOGIN_URL }}" \
                   class="nav-link">{% trans 'Войти' %}</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>

proplan/templates/proplan/_table_pagination.html
{% load i18n proplan_nav %}
<nav aria-label="{% trans 'Постраничная нумерация' %}">
    <ul class="pagination pagination-sm justify-content-end">
        <li class="mr-1">
            <div class="dropdown">
            {% with 'dropdown'|guid as id %}
                <button class="btn btn-secondary btn-sm" type="button" id="{{ id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span>{{ page.paginator.per_page }} {% trans 'на страницу' %}</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="{{ id }}">
                {% for v in '5,10,15,25,50,100,250,500'|split %}
                    <a class="dropdown-item" href="{% addparams request l=v %}">{{ v }}</a>
                {% endfor %}
                </div>
            {% endwith %}
            </div>
        </li>
{% for p in page|make_page_range %}
    {% if p == page.number %}
        <li class="page-item active"><a class="page-link text-light bg-dark" href="{% addparams request p=p %}">{{ p }}</a></li>
    {% elif p == '.' %}
        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
    {% else %}
        <li class="page-item"><a class="page-link text-muted" href="{% addparams request p=p %}">{{ p }}</a></li>
    {% endif %}
{% endfor %}
    </ul>
</nav>

proplan/templates/proplan/attachments.html
{% extends './base.html'%}
{% load i18n proplan_nav %}

{% block body_class %}attachments{% endblock %}

{% block content %}
{% url 'proplan:attachments' as path %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans 'Вложения' %}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{ path }}{% delparams request 'user_id' %}" class="btn btn-sm btn-outline-secondary {% if not filters.user_id %}active{% endif %}">{% trans 'все' %}</a>
            <a href="{{ path }}{% addparams request user_id=user.id %}" class="btn btn-sm btn-outline-secondary {% if filters.user_id == user.id|stringformat:'s' %}active{% endif %}">{% trans 'свои' %}</a>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-calendar"></span>
            <span class="ml-1"></span>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a href="{{ path }}{% delparams request 'created__lt' %}" class="dropdown-item {% if not filters.created__lt %}active{% endif %}">{% trans 'На сейчас' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_0 %}" class="dropdown-item {% if filters.created__lt == week_0 %}active{% endif %}">{% trans '1 неделю назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_1 %}" class="dropdown-item {% if filters.created__lt == week_1 %}active{% endif %}">{% trans '2 недели назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_2 %}" class="dropdown-item {% if filters.created__lt == week_2 %}active{% endif %}">{% trans '3 недели назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_0 %}" class="dropdown-item {% if filters.created__lt == month_0 %}active{% endif %}">{% trans '1 месяц назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_1 %}" class="dropdown-item {% if filters.created__lt == month_1 %}active{% endif %}">{% trans '2 месяца назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_2 %}" class="dropdown-item {% if filters.created__lt == month_2 %}active{% endif %}">{% trans '3 месяца назад' %}</a>
        </div>
    </div>
</div>

<table class="table table-striped mb-3">
    <thead class="bg-dark text-white">
        <tr>
            <th>ID</th>
            <th>{% trans 'Файл' %}</th>
            <th>{% trans 'Пользователь' %}</th>
            <th>{% trans 'Задачи' %}</th>
            <th>{% trans 'Комментарии' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for attach in page.object_list %}
        <tr>
            <td>{{ attach.id }}</td>
            <td>{{ attach.name }}</td>
            <td>{{ attach.user|default:'' }}</td>
            <td>
            {% for t in attach.get_tasks %}
                <a href="{% url 'proplan:task' id=t.id %}" class="mr-1">{{ t.id }}</a>
            {% endfor %}
            </td>
            <td>
            {% for c in attach.get_comments %}
                <a href="{% url 'proplan:task' id=c.task_id %}#comment={{ c.id }}" class="mr-1">{{ c.id }}</a>
            {% endfor %}
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="5">
                <p class="text-danger mb-0"><strong>{% trans 'вложения не найдены' %}</strong></p>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% if page.object_list %}
    <tfoot>
        <tr>
            <td colspan="5" class="pr-0">{% include './_table_pagination.html' %}</td>
        </tr>
    </tfoot>
{% endif %}
</table>

{% endblock %}

proplan/templates/proplan/comments.html
{% extends './base.html'%}
{% load i18n proplan_nav proplan_html %}

{% block body_class %}comments{% endblock %}

{% block content %}{% newlineless %}{% spaceless %}
{% url 'proplan:comments' as path %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans 'Комментарии' %}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{ path }}{% delparams request 'user_id' %}" class="btn btn-sm btn-outline-secondary {% if not filters.user_id %}active{% endif %}">{% trans 'все' %}</a>
            <a href="{{ path }}{% addparams request user_id=user.id %}" class="btn btn-sm btn-outline-secondary {% if filters.user_id == user.id|stringformat:'s' %}active{% endif %}">{% trans 'свои' %}</a>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-calendar"></span>
            <span class="ml-1"></span>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a href="{{ path }}{% delparams request 'created__lt' %}" class="dropdown-item {% if not filters.created__lt %}active{% endif %}">{% trans 'На сейчас' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_0 %}" class="dropdown-item {% if filters.created__lt == week_0 %}active{% endif %}">{% trans '1 неделю назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_1 %}" class="dropdown-item {% if filters.created__lt == week_1 %}active{% endif %}">{% trans '2 недели назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=week_2 %}" class="dropdown-item {% if filters.created__lt == week_2 %}active{% endif %}">{% trans '3 недели назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_0 %}" class="dropdown-item {% if filters.created__lt == month_0 %}active{% endif %}">{% trans '1 месяц назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_1 %}" class="dropdown-item {% if filters.created__lt == month_1 %}active{% endif %}">{% trans '2 месяца назад' %}</a>
            <a href="{{ path }}{% addparams request created__lt=month_2 %}" class="dropdown-item {% if filters.created__lt == month_2 %}active{% endif %}">{% trans '3 месяца назад' %}</a>
        </div>
    </div>
</div>

<table class="table table-striped mb-3">
    <thead class="bg-dark text-white">
        <tr>
            <th>ID</th>
            <th>{% trans 'Комментарий' %}</th>
            <th>{% trans 'Пользователь' %}</th>
            <th>{% trans 'Задача' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for comment in page.object_list %}
        <tr>
            <td>{{ comment.id }}</td>
            <td>
                <a href="{% url 'proplan:task' id=comment.task_id %}#comment-{{ comment.id }}"> \
                    {{ comment.message|markdown|striptags|truncatewords:20 }} \
                </a>
            </td>
            <td>{{ comment.user.get_full_name|default:comment.user|default:'' }}</td>
            <td>
                <a href="{% url 'proplan:task' id=comment.task_id %}">
                    <span>{{ comment.task }}</span>
                {% if comment.changes %}
                    <span class="badge bg-warning ml-1" title="{% trans 'Задача изменена.' %}">
                        <span class="fa fa-edit"></span>
                    </span>
                {% endif %}
                </a>
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">
                <p class="text-danger mb-0"><strong>{% trans 'комментарии не найдены' %}</strong></p>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% if page.object_list %}
    <tfoot>
        <tr>
            <td colspan="4" class="pr-0">{% include './_table_pagination.html' %}</td>
        </tr>
    </tfoot>
{% endif %}
</table>

{% endspaceless %}{% endnewlineless %}{% endblock %}

proplan/templates/proplan/password_change_form.html
{% extends './base.html'%}
{% load i18n proplan_bootstrap4 %}

{% block body_class %}profile{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans 'Форма изменения пароля' %}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{% url 'proplan:profile' %}" class="btn btn-sm btn-outline-secondary">
                <span>{% trans 'перейти в профиль' %}</span>
            </a>
        </div>
    </div>
</div>

<form class="form p-2" role="form" method="post" enctype="multipart/form-data">
    <input type="hidden" name="next" value="{{ next|escape }}" />
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    {% for field in form.visible_fields %}{{ field|form_group }}{% endfor %}
    <button type="submit" class="btn btn-dark btn-block">
        <i class="fa fa-save" aria-hidden="true"></i> \
        {% trans 'Обновить пароль' %} \
    </button>
</form>
{% endblock %}

proplan/templates/proplan/search.html
{% extends './base.html'%}
{% load i18n proplan_html %}

{% block body_class %}search{% endblock %}

{% block content %}{% newlineless %}{% spaceless %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans 'Результаты поиска' %}</h1>
</div>

<h2>{% trans 'Задачи' %}</h2>
<section class="mb-3">
{% for task in tasks %}
    <p class="search-result">
        <a href="{% url 'proplan:task' task.id %}">{{ task.title }}</a>
        <br>
        <span class="pl-4">{{ task.description|truncatewords:25 }}</span>
    </p>
{% empty %}
    <p>{% trans 'не найдены' %}</p>
{% endfor %}
{% if tasks_other %}
    <p class="text-info">{% blocktrans trimmed count other=tasks_other %}
    Найдена ещё {{ other }} задача.
    {% plural %}
    Найдено {{ other }} других задач.
    {% endblocktrans %}</p>
{% endif %}
</section>

<h2>{% trans 'Комментарии' %}</h2>
<section class="mb-3">
{% for comment in comments %}
    <p class="search-result">
        <a href="{% url 'proplan:task' comment.task_id %}#comment-{{ comment.id }}">{{ comment.task.title }}</a>
        <br>
        <span class="pl-4">{{ comment.message|truncatewords:25 }}</span>
    </p>
{% empty %}
    <p>{% trans 'не найдены' %}</p>
{% endfor %}
{% if comments_other %}
    <p class="text-info">{% blocktrans trimmed count other=comments_other %}
    Найден ещё {{ other }} комментарий.
    {% plural %}
    Найдено {{ other }} других комментариев.
    {% endblocktrans %}</p>
{% endif %}
</section>

{% endspaceless %}{% endnewlineless %}{% endblock %}

proplan/templates/proplan/tasks.html
{% extends './base.html'%}
{% load i18n proplan_nav proplan_html %}

{% block body_class %}tasks{% endblock %}

{% block content %}
{% url 'proplan:tasks' as path %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans 'Задачи' %}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group">
            <a href="{% url 'proplan:add_task' %}" class="btn btn-sm btn-outline-secondary add-task">
                <span class="fa fa-plus"></span>
                <span class="ml-1">{% trans 'добавить задачу' %}</span>
            </a>
        </div>

        <div class="btn-group ml-2">
            <a href="{{ path }}{% delparams request 'author_id' %}" class="btn btn-sm btn-outline-secondary {% if not filters.author_id %}active{% endif %}">{% trans 'все' %}</a>
            <a href="{{ path }}{% addparams request author_id=user.id %}" class="btn btn-sm btn-outline-secondary {% if filters.author_id == user.id|stringformat:'s' %}active{% endif %}">{% trans 'свои' %}</a>
        </div>

        <div class="dropdown ml-2">
            <button type="button" id="dropdownMenuCreated" data-toggle="dropdown" \
                aria-haspopup="true" aria-expanded="false" \
                class="btn btn-sm btn-outline-secondary ml-2 dropdown-toggle \
                {% if filters.created__lt %}active{% endif %}">
                <span class="fa fa-calendar"></span>
                <span class="ml-1"></span>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuCreated">
                <a href="{{ path }}{% delparams request 'created__lt' %}" class="dropdown-item {% if not filters.created__lt %}active{% endif %}">{% trans 'На сейчас' %}</a>
                <a href="{{ path }}{% addparams request created__lt=week_0 %}" class="dropdown-item {% if filters.created__lt == week_0 %}active{% endif %}">{% trans '1 неделю назад' %}</a>
                <a href="{{ path }}{% addparams request created__lt=week_1 %}" class="dropdown-item {% if filters.created__lt == week_1 %}active{% endif %}">{% trans '2 недели назад' %}</a>
                <a href="{{ path }}{% addparams request created__lt=week_2 %}" class="dropdown-item {% if filters.created__lt == week_2 %}active{% endif %}">{% trans '3 недели назад' %}</a>
                <a href="{{ path }}{% addparams request created__lt=month_0 %}" class="dropdown-item {% if filters.created__lt == month_0 %}active{% endif %}">{% trans '1 месяц назад' %}</a>
                <a href="{{ path }}{% addparams request created__lt=month_1 %}" class="dropdown-item {% if filters.created__lt == month_1 %}active{% endif %}">{% trans '2 месяца назад' %}</a>
                <a href="{{ path }}{% addparams request created__lt=month_2 %}" class="dropdown-item {% if filters.created__lt == month_2 %}active{% endif %}">{% trans '3 месяца назад' %}</a>
            </div>
        </div>

        <div class="dropdown ml-2">
            <button type="button" id="dropdownMenuSubprojects" \
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" \
                class="btn btn-sm btn-outline-secondary dropdown-toggle \
                {% if 'subproject' in filters %}active{% endif %}">
                <span class="fa fa-hashtag"></span>
            {% if subproject %}
                <span class="ml-1">{{ subproject }}</span>
            {% elif 'subproject' in filters and filters.subproject is None %}
                <span class="ml-1">{% trans 'Без подпроектов' %}</span>
            {% else %}
                <span class="ml-1">{% trans 'С подпроектами' %}</span>
            {% endif %}
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuSubprojects">
                <a href="{{ path }}{% delparams request 'subproject' %}" class="dropdown-item {% if 'subproject' not in filters %}active{% endif %}">{% trans 'С подпроектами' %}</a>
                <a href="{{ path }}{% addparams request subproject='null' %}" class="dropdown-item {% if 'subproject' in filters and filters.subproject is None %}active{% endif %}">{% trans 'Без подпроектов' %}</a>
            {% for sub in subprojects %}
                <a href="{{ path }}{% addparams request subproject=sub.id %}" class="dropdown-item {% if filters.subproject == sub.id %}active{% endif %}">{{ sub }}</a>
            {% endfor %}
            </div>
        </div>
    </div>
</div>


<table class="table mb-3">
    <thead class="bg-dark text-white">
        <tr>
            <th>ID</th>
            <th>{{ _('Название') }} / <br>{{ _('Описание') }}</th>
            <th>{{ _('Приоритет') }}</th>
            <th>{{ _('Трекер') }} / {{ _('Стадия') }}</th>
            <th class="text-right">{{ _('Изменений') }} / {{ _('Комментариев') }}</th>
        </tr>
    </thead>
    <tbody id="tasks">
    {% for task in page.object_list %}
        <tr>
            <td>{{ task.id }}</td>
            <td>
                <a href="{% url 'proplan:task' task.id %}">{{ task.title }}</a>
                <p class="pl-4 mb-0">{{ task.description|markdown|striptags|truncatewords:25 }}</p>
            </td>
            <td>{{ task.get_priority_display }}</td>
            <td>{{ task.tracker }}<br>{{ task.stage }}</td>
            <td class="text-right">{{ task.num_changes }}/{{ task.num_comments }}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="5">
                <p class="text-danger mb-0"><strong>{% trans 'задачи не найдены' %}</strong></p>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% if page.object_list %}
    <tfoot>
        <tr>
            <td colspan="5" class="pr-0">{% include './_table_pagination.html' %}</td>
        </tr>
    </tfoot>
{% endif %}
</table>

{% endblock %}